spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fmusic
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: env,info,health
